[package]
name = "code_writer"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
parser.workspace = true

[dev-dependencies]
rand.workspace = true