[package]
name = "parser"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true

[dev-dependencies]
rand.workspace = true